### ISSUE TITLE
Generate android-chrome-maskable PNGs and safari-pinned-tab SVG

### ISSUE THREAD

**Issue by dtgay** [jcalixte/vue-pwa-asset-generator#1]
**Is your feature request related to a problem? Please describe.**
Three files included with the Vue CLI setup of a PWA are not generated by `vue-pwa-asset-generator`:
- `android-chrome-maskable-192x192.png`
- `android-chrome-maskable-512x512.png`
- `safari-pinned-tab.svg`

**Describe the solution you'd like**
I would like these three files to be generated as well.

**Describe alternatives you've considered**
Could manually make them but that seems kind of silly, considering the purpose of this project. 🤷‍♂️

**Additional context**
Generated icons via this command, but the output lacked the three files mentioned above:
```sh
npx vue-pwa-asset-generator -a Desktop/icon.png -o icons
```

**Comment by jcalixte** [comment]
Hi dtgay!

Thanks for the report. You're right, these images are missing. I'll create a PR to add the maskable png.

Also, I'll take a look at generating the svg file from a png. Maybe [potrace](https://www.npmjs.com/package/potrace) does the job.

**Comment by jcalixte** [comment]
@dtgay these icons are now generated in 1.0.0 version!

**Comment by dtgay** [comment]
@jcalixte How about that for turn-around time! Awesome! Thanks!

**Comment by boxsnake** [comment]
One possible way is:
1. Go https://www.pwabuilder.com/imageGenerator to generate images with icons.json
2. Unzip the archieve to `public/img/icons`
3. Add following code to `vue.config.js`:
```js
let iconConfig = require('./public/img/icons/icons.json')

// Deal with icon paths
iconConfig.icons = iconConfig.icons.map(conf => {
  conf.src = `img/icons/${conf.src}`
  return conf
})
```
4. Add followings to `pwa` config in `vue.config.js`
```js
...
pwa: {
    manifestOptions: {
      icons: iconConfig.icons
    }
}
```

**NOTE** You may change the icon paths, `public/img/icon` is as an example.
