### ISSUE TITLE
bg image

### ISSUE THREAD

**Issue by marcomilone** [jcalixte/vue-pwa-asset-generator#18]
First,
thanks for that package.
I was using my python script in the past, this one is way more comfortable.

The idea:

Default background is white, for targets that doesn't support transparency.

I'll like to have another command line option ( -bg  ?)
to provide a secondary image.

That image, in my suggestion, should melt with the primary image, to compose the final image.

Ciaooo!

**Comment by jcalixte** [comment]
Hi!

It's a good idea, to be sure I understand: you want to customize the fallback background color for, and only for, images that don't support transparent background?

Do you think the option can be named `--fallback-background`? I'll take a look of what can be done.

**Comment by marcomilone** [comment]
Hello,
thanks for getting back.

Yes, that was the idea.

Just give a though, maybe is not so important,
the only image affected is favicon.ico as far as I see...?

Btw thanks for the package, works really well.

**Comment by jcalixte** [comment]
I think I can do the change this we, I'll keep you in touch.

**Comment by jcalixte** [comment]
Hi Marco, the `-b` option is now available in 1.7.1 to provide a background color (simpler than providing a secondary image), so you can customize the favicon background. Hope it provides what you needed!

Cheers!
