### ISSUE TITLE
favicon.svg

### ISSUE THREAD

**Issue by picks44** [jcalixte/vue-pwa-asset-generator#19]
**Is your feature request related to a problem? Please describe.**
It seems like the new Vue PWA plugin requires a favicon.svg asset now... Could you provide it through your tool?

**Describe the solution you'd like**
Add a favicon.svg asset (from a icon.svg base asset maybe?)

**Describe alternatives you've considered**
Manual action...

**Additional context**
Using "@vue/cli-plugin-pwa": "~5.0.0",

**Comment by jcalixte** [comment]
Hi there!

Is the new `favicon.svg` any different from the `safari-pinned-tab.svg` that is generated right now? If not, is a simple new naming enough?

**Comment by jcalixte** [comment]
I'm out of office, do you think you can do the PR?
