### ISSUE TITLE
android-chrome-512x512.png is deleted when the -b flag is not used

### ISSUE THREAD

**Issue by dennisalp** [jcalixte/vue-pwa-asset-generator#22]
```
vue-asset-generate -a logo.png -o test
```
gives all files except android-chrome-512x512.png (it is created but instantly deleted)

```
vue-asset-generate -a logo.png -o test -b "#3a3a3a"
```
gives all files (correct)

Something wrong with generateFavicon under script/modules/favicon.js when called from script/index.js I think 

```
if (background)
```
on line 17 must resolve to true to prevent android-chrome-512x512.png from being deleted

**Comment by jcalixte** [comment]
Hi Dennis,

Thanks for reporting this issue, it should be ok with the version 1.7.3.

Tell me if it's good for you.

Cheers.
