### ISSUE TITLE
Support SVG for Intake Asset

### ISSUE THREAD

**Issue by davidmyersdev** [jcalixte/vue-pwa-asset-generator#3]
#### Is your feature request related to a problem? Please describe.

My base icon is an SVG. To use this tool, I have to do the following.

- Convert the SVG (`icon.svg`) to a PNG (`icon-512x512.png`)
- Run `vue-asset-generate -a ./icon-512x512.png -o ./icons/`
- Replace the generated SVG with the original: `cp icon.svg ./icons/safari-pinned-tab.svg`

#### Describe the solution you'd like

Ideally, this feature would allow me to use an SVG as my intake asset. E.g.

```
vue-asset-generate -a ./icon.svg -o ./icons/
```

It would also use the intake SVG for the generated `safari-pinned-tab.svg` asset.

#### Describe alternatives you've considered

I am doing this manually at the moment (npm scripts). This package is wonderful, and I feel like it makes sense to support multiple intake asset types.

**Comment by jcalixte** [comment]
Hi there!

Thank you for your feedback, it is a good idea to handle multiple formats. I'll take a look! 😃

**Comment by jcalixte** [comment]
Okay, it's live on the 1.1.0 version! 🚀

**Comment by davidmyersdev** [comment]
Thanks for implementing this so quickly! I will update my build config and let you know how it turns out.
